apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.ca_arn }}
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{ .Values.sourcePort }}
  - name: https
    protocol: TCP
    port: 443
    targetPort: {{ .Values.sourcePort }}
  type: LoadBalancer
